mod commands;
pub mod core;
pub mod error;
mod pty;
mod shellout;
mod state;
mod watcher;

#[cfg(test)]
mod testutil;

use state::AppState;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .plugin(tauri_plugin_dialog::init())
        .manage(AppState::default())
        .invoke_handler(tauri::generate_handler![
            commands::open_repo,
            commands::git_available,
            commands::init_repo,
            commands::clone_repo,
            commands::list_refs,
            commands::get_graph,
            commands::search_commits,
            commands::cancel_search,
            commands::get_commit,
            commands::get_commit_diff,
            commands::get_worktree_diff,
            commands::compare_commits,
            commands::get_status,
            commands::stage_paths,
            commands::unstage_paths,
            commands::discard_paths,
            commands::ignore_path,
            commands::commit,
            commands::commit_template,
            commands::commit_advanced,
            commands::get_head_message,
            commands::set_upstream,
            commands::unset_upstream,
            commands::apply_patch,
            commands::create_branch,
            commands::delete_branch,
            commands::rename_branch,
            commands::checkout,
            commands::merge_ref,
            commands::merge_advanced,
            commands::cherry_pick,
            commands::cherry_pick_many,
            commands::reset_to,
            commands::rebase_onto,
            commands::rebase_continue,
            commands::rebase_abort,
            commands::abort_operation,
            commands::revert_commit,
            commands::rewrite_info,
            commands::rebase_commits,
            commands::predict_rebase_conflicts,
            commands::rebase_standard,
            commands::interactive_rebase,
            commands::operation_info,
            commands::operation_continue,
            commands::operation_skip,
            commands::operation_abort,
            commands::conflict_set,
            commands::get_conflict_file,
            commands::resolve_conflict_content,
            commands::resolve_conflict_side,
            commands::checkout_advanced,
            commands::create_patch,
            commands::create_tag,
            commands::delete_tag,
            commands::get_remote_url,
            commands::list_remotes,
            commands::add_remote,
            commands::remove_remote,
            commands::rename_remote,
            commands::set_remote_url,
            commands::push_target,
            commands::list_worktrees,
            commands::list_submodules,
            commands::update_submodules,
            commands::create_worktree,
            commands::worktree_holding,
            commands::remove_worktree,
            commands::wip_rows,
            commands::resolve_terminal_tokens,
            commands::blame_file,
            commands::file_history,
            commands::line_history,
            commands::path_at_commit,
            commands::list_contributors,
            commands::merge_target,
            commands::merge_relation,
            commands::autolink_patterns,
            commands::commit_stats,
            commands::file_at_commit,
            commands::stash_save,
            commands::stash_list,
            commands::stash_apply,
            commands::stash_pop,
            commands::stash_drop,
            commands::git_network,
            commands::cancel_git_network,
            commands::git_auto_fetch,
            commands::history_status,
            commands::clear_history,
            commands::undo,
            commands::redo,
            commands::get_settings,
            commands::save_settings,
            commands::get_identity,
            commands::set_identity,
            commands::watch_repo,
            commands::pty_spawn,
            commands::pty_write,
            commands::pty_resize,
            commands::pty_kill,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
